### ISSUE TITLE
Error using colab

### ISSUE THREAD

**Issue by lorrp1** [SystemErrorWang/CartoonGAN#12]
hello, im trying the "!python cartoonize_random_size.py"
i got this error: 

> Traceback (most recent call last):
>   File "cartoonize_random_size.py", line 82, in <module>
>     cartoon_image = cartoonize(image_path, weight_path)
>   File "cartoonize_random_size.py", line 63, in cartoonize
>     weight = np.load(weight_path)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 453, in load
>     pickle_kwargs=pickle_kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/format.py", line 722, in read_array
>     raise ValueError("Object arrays cannot be loaded when "
> ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by lorrp1** [comment]
solved with numpy==1.15.0
