### ISSUE TITLE
!

### ISSUE THREAD

**Issue by lxy443626128** [SystemErrorWang/CartoonGAN#4]
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    main()
  File "main.py", line 200, in main
    model.train()
  File "main.py", line 129, in train
    photo_batch = utils.next_batch(self.batch_size, self.image_size, self.celeba_list)
  File "/export/duoduo/lxy/CartoonGAN/utils.py", line 76, in next_batch
    return np.asarray(batch_data)
  File "/export/duoduo/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (96,96,3) into shape (96)

**Comment by SystemErrorWang** [comment]
This code works fine with my environment. I noticed that your are working on python 2.7, while I am working with python 3.6. This might have caused the error.

**Comment by lxy443626128** [comment]
Another question:
How can I test the images?

**Comment by SystemErrorWang** [comment]
I added a simple test function, and also some test results
